function testData(){
    
var babyData = {        //testData
    mothersFirstName: "Mary",
    mothersLastName: "Brown",
    mothersAge: 32,
    patientMedicalRecordNumber: 14304791,
    dateOfBirth: new Date(2017, 09, 12),
    patientsName: "Baby Mary Brown",
    dateOfAdmission: new Date(2017, 09, 15),
    dateOfInitialDisposition: new Date(2017, 09, 15),
    invasiveVentilation: 1,
    sepsisDuringAdmission: 1,
    immunizations652: 1,
    chromosomesDone: 1,
    abnormalHeadUltrasound: 1,
    fetalMedicineUnitFlagged:1,
    jaundiceNeedingPhototherapy: 1,
    
    
dayOfLifeVentilationStarted: 2,
dayOfLifeVentilationStartedDuration: 4,
dayOfLifeVentilationStartedDiagnosis: "The Diagnosis here",
    
  birthYear: 2018,
  birthWeightInGrams: 900,
  gestationalAgeInWeeks: 27,
  gestationalAgePlusDays: 2,
  diedInDeliveryRoom: 0,
  outbornBirth: 1,
  transferCenterCode: 13240,
  transferCenterName: "Mowbray Maternity Hospital",
  dayOfAdmission: 2,
  headCircumferenceAtBirth: 23.8,
  maternalRaceOfMother: 7,
  prenatalCare: 1,
  antenatalSteroids: 0,
  antenatalMagnesiumSulfate: 0,
  chorioamnionitis: 0,
  maternalHypertension: 1,
  maternalDiabetes: 0,
  modeOfDelivery: 0,
  sexOfInfant: 1,
  multipleGestation: 1,
  numberOfBirthsDelivered: 2,
  congenitalInfection: 0,
  congenitalInfectionOrg1: 7777,
  congenitalInfectionOrg2: 7777,
  congenitalInfectionOrg3: 7777,
  apgarScoresOneMin: 7,
  apgarScoresFiveMin: 9,
  oxygenDuringInitialResuscitation: 1,
  facemaskVentilation: 1,
  LaryngealMaskAirway: 0,
  endotrachealTubeVentilation:0,
  epinephrine:0,
  cardiacCompression:0,
  nasalVentilation: 0,
  nasalCpap: 0,
  temperatureMeasuredAtAdmissionState: 1,
  temperatureMeasuredAtAdmission: 35.9,
  bacterialSepsis: 1,
  bacterialSepsisPathogen1: 7777,
  bacterialSepsisPathogen2: 7777,
  bacterialSepsisPathogen3: 7777,
  oxygenOnDay28: 1,
  cranialImagning:1,
  periventricularHemorrhage: 2,
  pihOccurance: 1,
  diedWithin12Hours: 0,
  receivedOxygen: 1,
  conventionalVentilation: 1,
  highFrequencyVentilation: 0,
  highFlowNasalCannula: 0,
  nasalIMV: 0,
  nasalCPAPafterResuscitation: 1,
  nasalCPAPnoETT: 1,
  surfactant: 0,
  surfactantAtAnyTime: 1,
  ageAtSurfactantInHours: 7,
  ageAtSurfactantPlusMinutes: 0,
  inhaledNitricOxide: 0,
  inhaledNitricOxideWhereGiven: 7,
  oxygenAt36Weeks: 1,
  ventilationAt36Weeks: 0,
  highFrequencyVentilationAt36Weeks: 0,
  highFlowNasalCannulaAt36weeks: 1,
  nasalIMVAt36Weeks: 0,
  nasalCpapAt36Weeks: 0,
  steroidsForCLD: 0,
  steroidsForCLDWhereGiven: 7,
  indomethacin: 0,
  ibuprofen: 0,
  Acetaminophen: 0,
  probiotics: 1,
  ropTreatmentWithVegfDrug: 0,
  caffeine: 0,
  vitaminA: 0,
  ropSurgery: 0,
  ropSurgeryWhereDone: 7,
  pdaSurgery: 0,
  necSurgery: 0,
  otherSurgery: 0,
  firstSurgeryCode: 77,
  firstSurgeryLocation: 7,
   firstSurgerySiteInfection: 7,
  secondSurgery: 77,
  secondarySurgeryLocation: 7,
    secondarySurgerySiteInfection:7,
  thirdSurgery: 77,
  thirdSurgeryLocation: 7,
    thirdSurgerySiteInfection: 7,
  fourthSurgery: 77,
  fourthSurgeryLocation: 7,
    fourthSurgerySiteInfection: 7,
  fifthSurgery: 77,
  fifthSurgeryLocation: 7,
    fifthSurgerySiteInfection: 7,
  sixthSurgery: 77,
  sixthSurgeryLocation: 7,
    sixthSurgerySiteInfection: 7,
  seventhSurgery: 77,
  seventhSurgeryLocation: 7,
    seventhSurgerySiteInfection:7,
  eighthSurgery: 77,
  eighthSurgeryLocation: 7,
    eighthSurgerySiteInfection:7,
  ninethSurgery: 77,
  ninethSurgeryLocation: 7,
    ninethSurgerySiteInfection:7,
  tenthSurgery: 77,
  tenthSurgeryLocation: 7,
    tenthSurgerySiteInfection:7,
  otherSurgeryDescription: 77,
  respiratoryDistressSyndrome: 1,
  pneumothorax: 0,
  pneumothoraxWhereOccured: 7,
  patentDuctusArteriosus: 1,
  necrotizingEnterocolitis: 0,
  necrotizingEnterocolitisWhereOccured: 7,
  focalIntestinalPerforation: 0,
  focalIntestinalPerforationWhereOccured: 7,
  bacterialPathogenAfterDay3: 0,
  bacterialPathogenAfterDay3WhereOccured: 7,
  bacterialPathogenAfterDay3Pathogen1: 7777,
  bacterialPathogenAfterDay3Pathogen2: 7777,
  bacterialPathogenAfterDay3Pathogen3: 7777,
  coagulaseNegativeStaphInfection: 1,
  coagulaseNegativeStaphInfectionWhereOccured:1,
  fungalInfection: 0,
  fungalInfectionWhereOccured: 7,
  cysticPeriventricularLeukomalacia: 0,
  retinalExamination:1,
  ropStage: 2,
  majorBirthDefect: 0,
  firstBirthDefectCode: 7777,
  secondBirthDefectCode: 7777,
  thirdBirthDefectCode: 7777,
  fourthBirthDefectCode: 7777,
  fifthBirthDefectCode: 7777,
  birthDefectDescription: 77,
  enteralfeeding: 3,
  oxygenAtDischarge: 0,
  conventionalVentilationAtDischarge: 0,
  highFrequencyVentilationAtDischarge: 0,
  highFlowNasalCannulaAtDischarge: 0,
  nasalVentilationAtDischarge: 0,
  nasalCpapAtDischarge: 0,
  monitorAtDischarge: 0,
  initialDisposition: 2,
  weightAtInitialDisposition: 1000,
  headCircumferenceAtInitialDisposition: 24.8,
  initialLengthOfStay: 13,
  reasonForTransfer: 1,
  newTransferCenterCode: 77777777
//     fetalMedicineUnitFlagged,
//  antenatalScan,
//  postnatalScan,
//  chromosomesDone,
//  hearingScreen,
//  hearingScreenResult,
//  jaundiceNeedingPhototherapy,
//  levelAboveExchange,
//  hypoxicIschaemicEncephalopathy,
//  hypoxicIschaemicEncephalopathyHighestScore,
//  cooled,
//  CFM48Hours,
//  CFMHighestScore,
//  
//  numberOfEpisodes,
//  meningitis,
//  organismCode1,
//  organismCode2,
//  organismCode3,
//  
//  dayOfLifeVentilationStarted,
//  dayOfLifeVentilationStartedDuration,
//  dayOfLifeVentilationStartedDiagnosis,
//  mothersAge,
//  grav,
//  para,
//  RVD,
//  viralLoad,
//  babyPCR,
//  immunizations652,
//  immunizations652Date,
//  appointmentLocation,
//  appointmentDate,
//  immunizationDate,
//  PCRDate,
//  ROPDate


  // postTransferDisposition: 1,
  // dispositionAfterReadmission: 7,
  // weightAtDispositionAfterReadmission: 77777,
  // ultimateDisposition: 7,
  // totalLengthOfStay: 100,
  // durationOfAssistedVentilation: 7,
  // daysOfAssistedVentilation: 7777,
  // ecmoAtHospital: 7,
  // hypothermicTherapy: 0,
  // coolingMethod: 7,
  // hypoxicIschemicEncephalopathyHighestScore: 7,
  // hieSeverity: 7,
  // meconiumAspirationSyndrome: 7,
  // trachealSuctioningAttempted: 7,
  // seizures: 7
};
    return babyData;
}